# 1. 函数

## 1.1 什么是函数

特性：

- 不支持嵌套、重载和默认参数
- 无需声明原型、不定长度变参、多返回值、命名返回参数、匿名函数、闭包
- 本身就是一种类型



**函数调用底层分析：**

- 栈区：基本数据类型一般分配到栈区。编译器存在一个逃逸分析。每个函数有独立的栈，函数执行完毕，自动销毁
- 堆区：引用数据类型一般分配在堆区
- 代码区：存放代码指令



## 1.2 参数传递

不管是指针、引用类型，还是其他类型参数，都是值拷贝传递（pass-by-value)。区别无非是拷贝目标对象，还是拷贝指针对象本身而已。

在函数调用时，会为形参和返回值分配内存空间，并将实参拷贝到形参的内存。



## 1.3 参数过多，改用struct

```go
type serverOption struct {
	ip       string
	port     int
	path     string
	timeout  time.Duration
	log      *log.Logger
}

func newOption() *serverOption {
	return &serverOption{
		ip: "0.0.0.0",
		port: 8080,
		path: "/data/www",
		timeout: time.Second*5,
		log: nil,
	}
}

func server(option *serverOption) {}

func main() {
	opt := newOption()
	opt.port = 8080

	server(opt)
}
```



## 1.4 变参

变参，实际上传递的是一个slice，如果是array，先转化为slice。`s := a[:]...`

```go
func test(a ...int) {
	fmt.Printf("%T, %v\n", a, a)
}

func main() {
	test(1, 2, 3, 4)
  
	a := [3]int {10, 20, 30}
	test(a[:]...)
}
```



# 2. 匿名函数

## 2.1 直接执行

```go
func main() {
	func (s string) {
		println(s)
	} ("Hello world")
}
```



## 2.2 赋值给变量

```go
func main() {
	add := func (x, y int) int {
		return x + y
	}

	println(add(2, 3))
}
```



## 2.3 作为参数

```go
func test(f func()) {
	f()
}

func main() {
	test(func() {
		println("Hello world")
	})
}
```



## 2.4 作为返回值

```go
func test(x, y int) func() int {
	return func() int {
		return x + y
	}
}

func main() {
	add := test(2, 3)
	println(add())
}
```



## 2.5 作为结构体字段

```go
func testStruct() {
	type calc struct {
		mul func(x, y int) int
	}

	z := calc {
		mul: func(x, y int) int {
			return x * y
		},
	}

	println(z.mul(2, 5))
}
```



## 2.6 通过Channel传递

```go
func testChannel() {
	c := make(chan func(int, int) int, 2)

	c <- func(a int, b int) int {
		return a + b
	}

	println((<- c)(1, 2))
}
```



# 3. 闭包（closure）

a **closure** is a record storing **a function** together with **an environment**. **闭包**是由**函数**和与其相关的引用**环境**组合而成的实体 。

闭包是一个函数值，它引用了函数体之外的变量。 这个函数可以对这个引用的变量进行访问和赋值；换句话说这个函数被“绑定”在这个变量上。

- 返回一个匿名函数
- 该**匿名函数使用了函数外变量**



## 3.1 闭包求值

```go
func main() {
	f := closure(10)
	fmt.Println(f(1)) // 11
	fmt.Println(f(2)) // 12
}

func closure(x int) func(int) int {
	fmt.Printf("%p\n", &x) // 0xc0000140b0
	return func(y int) int {
		fmt.Printf("%p\n", &x) // 0xc0000140b0
		return x + y
	}
}
```



## 3.2 多匿名函数返回，延迟求值

```go
func test() []func() {
	var fs []func()

	for i := 0; i < 3; i++ {
		fs = append(fs, func() {
			println(&i, i)    // 延迟执行特性，最后都输出3
		})
	}

	return fs
}

func main() {
	for _, f := range test() {
		f()
	}
}
```

修正后：

```go
func test() []func() {
	var fs []func()

	for i := 0; i < 3; i++ {
		i := i  // 赋值重写
		fs = append(fs, func() {
			println(&i, i)
		})
	}

	return fs
}

func main() {
	for _, f := range test() {
		f()
	}
}
```



## 3.3 延迟求值

```go
func test() []func() {
	var funcs []func()

	for i := 0; i < 2; i++ {
		x := i // re-assignment
		funcs = append(funcs, func() {
			//fmt.Printf("%p, %v\n", &i, i) // xxx, 2
			fmt.Printf("%p, %v\n", &x, x) // xxx, 0; yyy, 1
		})
	}

	return funcs
}
```



## 3.4 引用同一变量

```go
func test(x int) (func(), func()) {
	return func() {
			fmt.Println(x)
			x += 10
		}, func() {
			fmt.Println(x) // x+10
		}
}
func main() {
	a, b := test(100)
	a() // 100
	b() // 110
}
```



# 4. 递归

## 4.1 阶乘

```go
func factorial(n uint64) uint64 {
	if n > 0 {
		return n * factorial(n - 1)
	}

	return 1
}

func main() {
	var i int = 15
	fmt.Printf("%d 的阶乘等于 %d", i, factorial(uint64(i)))
}
```



## 4.2 Fibonacci

```go
func fibonacci(n uint64) uint64 {
	if n < 2 {
		return n
	}

	return fibonacci(n-2) + fibonacci(n-1)
}

func main() {
	for i := 0; i < 10; i++ {
		fmt.Printf("%d ", fibonacci(uint64(i)))
	}
	fmt.Println()
}
```



# 5. 延迟调用（defer)

defer： 延迟调用

- FILO 先进后出
- 即使函数发生panic错误，也会执行
- 支持匿名函数调用
- 用于资源清理、文件关闭、解锁以及记录时间等操作
- 与匿名函数配合，可在return后修改函数的计算结果



## 5.1 性能

相比直接用CALL汇编指令调用函数，延迟调用则须花费更大代价。这其中包括注册、调用等操作，还有额外的缓存开销。

```go
var m sync.Mutex

func call() {
	m.Lock()
	m.Unlock()
}

func deferCall() {
	m.Lock()
	defer m.Unlock()
}

func BenchmarkCall(b *testing.B) {
	for i := 0; i < b.N; i++ {
		call()
	}
}

func BenchmarkDeferCall(b *testing.B) {
	for i := 0; i < b.N; i++ {
		deferCall()
	}
}
```

```bash
$ go test -bench=. -v
BenchmarkCall
BenchmarkCall-4         94623559                12.5 ns/op
BenchmarkDeferCall
BenchmarkDeferCall-4    70848210                16.0 ns/op
```



## 5.2 defer 和 闭包
```go
func main() {
	var fns = [3]func(){}

	for i := 0; i < 3; i++ {
		// 4th, defer i = 2, 1, 0
		defer fmt.Println("defer i =", i)

		// 3rd, closure_without_arg_defer i = 3, 3, 3
		defer func() {
			fmt.Println("closure_without_arg_defer i =", i)
		}()

		// 2nd, closure_with_arg_defer i = 2, 1, 0
		defer func(i int) {
			fmt.Println("closure_with_arg_defer i =", i)
		}(i)

		fns[i] = func() {
			fmt.Println("closure i =", i)
		}
	}

	// 1st, but always "closure i = 3"
	for _, fn := range fns {
		fn()
	}
}
```



## 5.3 只延迟紧挨它的函数

```go
func calc(idx string, a, b int) int {
	ret := a + b
	fmt.Println(idx, a, b, ret)
	return ret
}

func main() {
	a, b := 1, 2

	defer calc("1", a, calc("10", a, b))

	a = 0

	defer calc("2", a, calc("20", a, b))

	b = 1
}

// Output:
// 10 1 2 3 => defer calc("1", 1, 3)
// 20 0 2 2 => defer calc("2", 0, 2)
// 2  0 2 2
// 1  1 3 4
```



## 5.4 连续多个表达式

按优先级执行，保留最后一个表达式给 defer

```go
type Slice []int

func NewSlice() Slice {
	return make([]int, 0)
}

func (s *Slice) Add(i int) *Slice {
	*s = append(*s, i)
	//fmt.Println(*s)
	return s
}

func test(s *Slice) {
	defer s.Add(1).Add(2)

	s.Add(3)

	fmt.Println(*s) // [1, 3]
}

func main() {
	s := NewSlice()

	test(&s)

	fmt.Println(s) // [1, 3, 2]
}
```



## 5.5 defer & return

`return`: `RETVAL=x` --> `RETURN`

`defer`:  `RETVAL=x` --> `defer` --> `RETURN`

**defer 需要在函数结束前执行。 函数返回值名字会在函数起始处被初始化为对应类型的零值并且作用域为整个函数**

**Golang**中**defer**、**return**、返回值之间执行**顺序**坑：

1. 多个**defer**的执行**顺序**为“后进先出”；
2. **defer**、**return**、返回值三者的执行逻辑应该是：**return**最先执行，**return**负责将结果写入返回值中；接着**defer**开始执行一些收尾工作；最后函数携带当前返回值退出。

**示例1：**

```go
func fn1(i int) (t int) {
	t = i
	defer func() {
		t += 3
	}()

	return t
}

func fn2(i int) int {
	t := i
	defer func() {
		t += 3
	}()

	return t
}

func fn3(i int) (t int) {
	defer func() {
		t += i
	}()

	// t 指向的对象
	return 2
}

func main() {
	fmt.Println(fn1(1)) // 4
	fmt.Println(fn2(1)) // 1
	fmt.Println(fn3(1)) // 3
}
```

**示例2：**


```go
// 1
func f1() (r int) {
  defer func() {
    r++
  }()
  return 0
}

// 5
func f2() (r int) {
  t := 5
  defer func() {
    t += 5
  }()
  return t
}

// 1
func f3() (r int) {
  defer func(r int) {
    r++ // 与 return 后的 r 不是一个
  }(r)
  return 1
}

// 7
func f4() (r int) {
	t := 5
	defer func() {
		r = t + 2
	}()
	return t
}
```

**示例3：**

```go
// 5
func demo1() int {
	x := 5
	defer func() {
		x += 1
	}()
	return x
}

// 6
func demo2() (x int) {
	defer func() {
		x += 1
	}()
	return 5
}

// 5
func demo3() (x int) {
	defer func(x int) {
		x += 1
	}(x)
	return 5
}
```



# 6. 错误处理

标准库错误接口:

```go
type error interface {
  Error() string
}
```



## 6.1 panic & recover

- panic: 主动抛出错误
- recover: 捕获panic抛出的错误

```go
func panic(v interface{})
func recover() interface{}
```

panic和recover运行机制：

1) 引发panic有两种情况：一是程序主动调用，二是程序产生运行时错误(Runtime Error)，由运行时检测并退出

2) 发生panic后，程序会从调用panic的函数位置或发生panic的地方立即返回，逐层执行函数的的defer语句，然后逐层打印函数调用堆栈，直到recover捕获或运行到最外层函数

3) panic不但可以在函数正常流程中抛出，在defer逻辑里也可以再次调用panic或抛出panic。defer里面的panic能够被后续执行的defer捕获

4) recover用来捕获panic，阻止panic继续向上传递。recover()和defer一起使用，但是defer只有在后面的函数体内直接被调用才能捕获panic来终止，否则返回nil，异常继续向外传递。

注意：除非是不可恢复性、导致系统无法正常工作的错误，否则不建议使用panic。如：文件系统没操作权限、服务端口被占用、数据库未启动等

```go
func main() {
	result := div(8, 0)
	fmt.Println(result)
}

func div(a int, b int) int {
	defer func() {
		err := recover()
		if err != nil {
			fmt.Println(err)
		}
	}()

	return a / b
}
```



## 6.2 主动panic并捕获

```go
func main() {
  defer func() {
    if err := recover(); err != nil {
      log.Fatalln(err)
    }
  }()
  
  panic("crash")
  println("exit.")
}
```



## 6.3 无效捕获和有效捕获错误

```go
// 无效的捕获
defer recover()
defer fmt.Println(recover())
defer func() {
	func() {
		recover()  // 嵌套多层，无效
	}()
}()

// 有效的捕获
defer func() {
	recover()
}()

func except() {
	recover()
}

func test() {
	defer except()
	panic("runtime error")
}
```



## 6.4 多个panic，只会捕获最后一个

```go
func main() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)  // three 只会捕获最后一个
		}
	}()

	defer func() {
		panic("three")
	}()

	defer func() {
		panic("two")
	}()

	panic("one")
}
```



## 6.5 自定义错误

- `errors.New("错误描述")`：返回一个error类型的值，表示一个错误
- `panic`内置函数：接收一个interface{}类型的值(即任意值)作为参数，可以接受error类型的变量，输出错误信息，并退出程序。

```go
func Sqrt(x float64) (float64, error) {
	if x < 0 {
		return 0, errors.New("math: square root of negative number")
	}

	return math.Sqrt(x), nil
}

func main() {
	result, err := Sqrt(-1)

	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(result)
	}
}
```
